### ISSUE TITLE
I become the following Failure. Any Idea?

### ISSUE THREAD

**Issue by maxis1601** [GreenScreen410/discord.js-v14-template#1]
Node.js v18.15.0
PS C:\Github\LSMD-DC-v14> node index.js
node:internal/modules/cjs/loader:1075
  const err = new Error(message);
              ^

Require stack:
- C:\Github\LSMD-DC-v14\commands\info\botStats.js
- C:\Github\LSMD-DC-v14\handler\index.js
- C:\Github\LSMD-DC-v14\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Github\LSMD-DC-v14\commands\info\botStats.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Github\\LSMD-DC-v14\\commands\\info\\botStats.js',
    'C:\\Github\\LSMD-DC-v14\\handler\\index.js',
    'C:\\Github\\LSMD-DC-v14\\index.js'
  ]
}

**Comment by maxis1601** [comment]
Fixed it. I needed to install  the modules :D
But now i got a new Error

C:\Github\LSMD-DC-v14\events\ready.js:4
    console.log(`${client.user.tag} is up and ready to go!`)
                                                           ^

SyntaxError: missing ) after argument list
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at C:\Github\LSMD-DC-v14\handler\index.js:27:31
    at Array.map (<anonymous>)

**Comment by maxis1601** [comment]
Fixed it. I needed to install the modules :D
But now i got a new Error

C:\Github\LSMD-DC-v14\events\ready.js:4
console.log(${client.user.tag} is up and ready to go!)
^

SyntaxError: missing ) after argument list
at internalCompileFunction (node:internal/vm:73:18)
at wrapSafe (node:internal/modules/cjs/loader:1176:20)
at Module._compile (node:internal/modules/cjs/loader:1218:27)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at C:\Github\LSMD-DC-v14\handler\index.js:27:31
at Array.map ()

**Comment by GreenScreen410** [comment]
``console.log(`${client.user.tag} is up and ready to go!`);``
You missed ``backtick(`)``.
